# Generated by Django 2.2.10 on 2020-05-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ServiceType',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('term_subscription', models.BooleanField(default=False)),
                ('subscription', models.CharField(max_length=255)),
                ('server_name_prefix', models.CharField(max_length=255)),
                ('package', models.IntegerField(default=1)),
                ('trunk_service_provider', models.IntegerField(default=1)),
                ('extra_call_record_package', models.IntegerField(default=1)),
                ('demo', models.BooleanField(default=False)),
                ('extra_duration_package', models.IntegerField(default=1)),
                ('servers', models.CharField(max_length=255)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.ServiceType')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
