# Generated by Django 2.2.10 on 2020-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetype',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='servers',
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.CharField(default='Not Initialized ', max_length=255),
        ),
    ]
